image: satantime/puppeteer-node:18.18.0-bullseye

stages:
  - build
  - test
  - integrationtest

before_script:
  - |
      # Test Whisker against a specific commit of the scratch-vm. Can be used
      # either by pipelines in other projects to trigger a downstream build
      # while using a specific commit, or when manually triggering a CI pipeline
      # via the GitLab UI.
      if [ -n "$SCRATCH_VM_COMMIT" ]; then
        echo "Changing scratch-vm version to $SCRATCH_VM_COMMIT"
        sed -i "s|se2/scratch/scratch-vm.git#develop|se2/whisker/scratch-vm.git#$SCRATCH_VM_COMMIT|" */package.json
      fi

      if [ -n "$SCRATCH_RENDER_COMMIT" ]; then
        echo "Changing scratch-render version to $SCRATCH_RENDER_COMMIT"
        sed -i "s|se2/scratch/scratch-render.git#develop|se2/scratch/scratch-render.git#$SCRATCH_RENDER_COMMIT|" */package.json
      fi
  - yarn install --cache-folder .yarn

cache:
  paths:
    - node_modules/
    - .yarn
    - .cache

build_all:
  stage: build
  script:
    - yarn install
    - mkdir -p output/static
    - yarn build-main
    - yarn build-web
  artifacts:
    expire_in: 1 hour
    paths:
      - whisker-main/dist
      - whisker-web/dist


unit-tests:
  stage: test
  script:
    - yarn test
    - mkdir -p output/static

integration-tests:
    stage: integrationtest
    script:
        - yarn integrationtest
