import {NeatPopulation} from "./NeatPopulation";
import {StatementFitnessFunction} from "../../../testcase/fitness/StatementFitnessFunction";
import {NeatChromosome} from "../networks/NeatChromosome";
import {ChromosomeGenerator} from "../../../search/ChromosomeGenerator";
import {Container} from "../../../utils/Container";
import {Randomness} from "../../../utils/Randomness";
import {NeatestParameter} from "../hyperparameter/NeatestParameter";
import {NeatParameter} from "../hyperparameter/NeatParameter";
import {BranchCoverageFitnessFunction} from "../../../testcase/fitness/BranchCoverageFitnessFunction";

export class NeatestPopulation extends NeatPopulation {

    constructor(generator: ChromosomeGenerator<NeatChromosome>, hyperParameter: NeatParameter,
                private readonly _allObjectives: number[],
                private readonly _targetedObjective: StatementFitnessFunction,
                private readonly _startingNetworks: NeatChromosome[],
                private readonly _randomFraction: number) {
        super(generator, hyperParameter);
    }

    /**
     * Generates an initial population of networks by cloning and mutating networks that
     * proved to be viable solutions for their targeted objective.
     * To not get stuck in certain network structures and to favour simple network structures,
     * we also generate some new networks.
     * In case we have not yet covered anything,
     * we just generate the desired number of networks using the defined NetworkGenerator.
     */
    public override async generatePopulation(): Promise<void> {
        // If we don't have any starting networks, i.e., it's the first ever selected fitness target generate
        // the desired number of networks using the defined generator.
        if (this._startingNetworks.length === 0) {
            while (this.networks.length < this.populationSize) {
                const network = await this.generator.get();
                this.networks.push(network);

                // Do not apply gradient descent for the first statement since it will always be the green flag,
                // which is covered trivially without further optimisations.
                if (this._targetedObjective instanceof BranchCoverageFitnessFunction) {
                    this.applyGradientDescent(network);
                }
            }
        } else {
            // Otherwise, we start with cloning all starting networks.
            for (const network of this._startingNetworks) {
                // Stop if we already hit the population boundary.
                if (this.networks.length >= this.hyperParameter.populationSize) {
                    break;
                }
                const clone = network.cloneStructure(true);
                this.networks.push(clone);
            }

            // Then, we fill our population with new networks based on the supplied randomFraction.
            const newNetworksSize = Math.floor(this._randomFraction * this.hyperParameter.populationSize);
            for (let i = 0; i < newNetworksSize; i++) {
                // Stop if we already hit the population boundary.
                if (this.networks.length >= this.hyperParameter.populationSize) {
                    break;
                }
                const network = await this.generator.get();

                this.applyGradientDescent(network);

                this.networks.push(network);
            }

            // The remaining networks are generated by mutating prior solutions.
            this._startingNetworks.forEach(network => network.gradientDescentChild = false);
            let i = 0;
            while (this.networks.length < this.hyperParameter.populationSize) {
                const parent = this._startingNetworks[i % this._startingNetworks.length];
                const mutant = await parent.mutate();
                this.networks.push(mutant);
                i++;
            }
        }

        // Finally, allocate the objective map, set the fitness to the targeted objective and speciate each
        // generated network.
        for (const network of this.networks) {
            network.initialiseCoverageObjectives(this._allObjectives);
            network.targetObjective = this._targetedObjective;
            this.assignSpecies(network);
        }
    }


    /**
     * Apply gradient descent with a given probability if it's enabled.
     * @param network The network that may be optimised via gradient descent.
     */
    private applyGradientDescent(network: NeatChromosome) {
        if (!Container.backpropagationInstance) {
            return;
        }

        const randomNumber = Randomness.getInstance().nextDouble();
        if (randomNumber <= (this.hyperParameter as NeatestParameter).gradientDescentParameter.probability) {
            Container.backpropagationInstance.gradientDescent(network, this._targetedObjective.getNodeId());
        }
    }
}
