import {TestGenerator} from "../../../testgenerator/TestGenerator";
import {TfAgentWrapper} from "../agents/TfAgentWrapper";
import {DeepQLearning} from "../algorithms/DeepQLearning";
import {RLEnvironment} from "./RLEnvironment";
import {RLTestSuite} from "./RLTestSuite";
import {DeepQLearningHyperparameter} from "../hyperparameter/DeepQLearningHyperparameter";
import {StatementFitnessFunction} from "../../../testcase/fitness/StatementFitnessFunction";
import {StatementFitnessFunctionFactory} from "../../../testcase/fitness/StatementFitnessFunctionFactory";
import {BranchCoverageFitnessFunctionFactory} from "../../../testcase/fitness/BranchCoverageFitnessFunctionFactory";
import {RLAlgorithm} from "../algorithms/RLAlgorithm";
import {CoverageDirectedDeepQLearning} from "../algorithms/CoverageDirectedDeepQLearning";
import Arrays from "../../../utils/Arrays";

export class RLTestGenerator extends TestGenerator {

    /**
     * Generates tests for the loaded Scratch project using Reinforcement Learning as an optimization algorithm.
     *
     * @returns a test suite containing all tests generated by the optimization algorithm.
     */
    async generateTests(): Promise<RLTestSuite> {
        this._vmWrapper.vm.registerCoverageTracer(false);
        const algorithm = this.buildOptimizationAlgorithm();
        const archive = await algorithm.findSolution();
        const trimmedArchive = Arrays.distinctObjects(archive.values()) as TfAgentWrapper[];
        console.log(`Generated ${trimmedArchive.length} tests.`);
        return new RLTestSuite(trimmedArchive);
    }

    /**
     * Builds and sets hyperparameter of the Reinforcement Learning algorithm to be used for generating tests.
     */
    override buildOptimizationAlgorithm(): RLAlgorithm<TfAgentWrapper> {
        let algorithm: RLAlgorithm<TfAgentWrapper>;
        const parameter = this._config.getRLHyperparameter() as DeepQLearningHyperparameter;
        if (this._config.getRLHyperparameter().rewardParameter.type === "coverage") {
            algorithm = new CoverageDirectedDeepQLearning(parameter, this._setupEnvironment());
        } else {
            algorithm = new DeepQLearning(this._config.getRLHyperparameter() as DeepQLearningHyperparameter, this._setupEnvironment());
        }
        algorithm.setFitnessFunctions(this._getCoverageObjectives());
        return algorithm;
    }

    /**
     * Initializes the Reinforcement Learning environment based on the specified parameter.
     */
    private _setupEnvironment(): RLEnvironment {
        return new RLEnvironment(this._vmWrapper, this._config.getRLHyperparameter().environmentParameter);
    }

    /**
     * Collects the coverage objectives from the loaded Scratch project based on the specified coverage type.
     *
     * @returns a map containing the coverage objectives.
     */
    private _getCoverageObjectives(): Map<number, StatementFitnessFunction> {
        const {type, targets} = this._config.getRLHyperparameter().coverageObjectives;
        const coverageFactory = type === "statement" ?
            new StatementFitnessFunctionFactory() : new BranchCoverageFitnessFunctionFactory();
        const objectives = coverageFactory.extractFitnessFunctions(this._vmWrapper.vm, targets);

        const objectiveMap = new Map<number, StatementFitnessFunction>();
        for (let i = 0; i < objectives.length; i++) {
            objectiveMap.set(i, objectives[i]);
        }

        return objectiveMap;
    }
}
