const test0 = async function (t) {
  await t.runForSteps(92);
  await t.runForSteps(1);
  t.keyPress('space', 1);
  await t.runForSteps(1);
  await t.runForSteps(1);
  await t.runForSteps(92);
  await t.runForSteps(1);
  t.keyPress('space', 8);
  await t.runForSteps(8);
  await t.runForSteps(1);
  t.keyPress('space', 1);
  await t.runForSteps(1);
  await t.runForSteps(1);
  t.keyPress('space', 9);
  await t.runForSteps(9);
  await t.runForSteps(1);
  t.keyPress('space', 9);
  await t.runForSteps(9);
  await t.runForSteps(1);
  t.keyPress('space', 1);
  await t.runForSteps(1);
  await t.runForSteps(1);
  await t.runForSteps(8);
  await t.runForSteps(1);
  t.keyPress('space', 6);
  await t.runForSteps(6);
  await t.runForSteps(1);
  t.keyPress('space', 9);
  await t.runForSteps(9);
  await t.runForSteps(1);
  await t.runForSteps(30);
  await t.runForSteps(1);
  await t.runForSteps(28);
  await t.runForSteps(1);
  await t.runForSteps(87);
  await t.runForSteps(1);
  t.keyPress('space', 4);
  await t.runForSteps(4);
  await t.runForSteps(1);
  await t.runForSteps(26);
  await t.runForSteps(1);
  t.keyPress('space', 3);
  await t.runForSteps(3);
  await t.runForSteps(1);
  await t.runForSteps(80);
  await t.runForSteps(1);
  t.keyPress('space', 9);
  await t.runForSteps(9);
  await t.runForSteps(1);
  await t.runForSteps(8);
  await t.runForSteps(1);
  t.keyPress('space', 8);
  await t.runForSteps(8);
  await t.runForSteps(1);
  await t.runForSteps(88);
  await t.runForSteps(1);
  t.keyPress('space', 2);
  await t.runForSteps(2);
  await t.runForSteps(1);
  await t.runForSteps(78);
  await t.runForSteps(1);
  t.keyPress('space', 3);
  await t.runForSteps(3);
  await t.runForSteps(1);
  t.keyPress('space', 6);
  await t.runForSteps(6);
  await t.runForSteps(1);
  await t.runForSteps(11);
  await t.runForSteps(1);
  await t.runForSteps(33);
  await t.runForSteps(1);
  t.keyPress('space', 7);
  await t.runForSteps(7);
  await t.runForSteps(1);
  await t.runForSteps(86);
  await t.runForSteps(1);
  t.keyPress('space', 9);
  await t.runForSteps(9);
  await t.runForSteps(1);
  t.keyPress('space', 8);
  await t.runForSteps(8);
  await t.runForSteps(1);
}

module.exports = [
  {
      test: test0,
      name: 'Generated Test',
      description: '',
      categories: [],
      generationAlgorithm: 'mosa',
      seed: '1670223094081',
      type: 'standard',
  }
]
